/**
 * Z-Chain ZK proof generator hook.
 *
 * Threat model:
 *   - Adversary watching the gateway: must not learn the witness (the
 *     underlying data the user is proving facts about). When `@l.x/zk`
 *     ships we generate proofs entirely client-side (in a Worker) and
 *     the gateway only sees the proof + public inputs.
 *   - Adversary inspecting the proof QR: must not be able to reconstruct
 *     the witness. Proofs are zero-knowledge by definition, and we only
 *     ship the proof + public inputs — no witness leakage.
 *
 * Defense:
 *   - When `@l.x/zk` is present, all proving happens in a Worker — we
 *     never touch the witness on the main thread.
 *   - When falling back to the gateway prover, the UI surfaces the
 *     degraded-mode warning. This mode is acceptable for non-sensitive
 *     claims (AgeGT18 with KYC backing, etc.) but NOT for BalanceGT.
 *
 * Heavy circuits (Halo2 / Groth16) take seconds. UI shows a determinate
 * progress bar driven by Worker postMessage events.
 */

import { useCallback, useState } from "react"
import { gatewayUrl } from "./brand"
import { confidentialStore } from "../../store/confidential"
import type { ClaimParams, ZKProof } from "./types"

interface ZKModule {
  prove(claim: ClaimParams, witness: unknown): Promise<{
    proof: string
    publicInputs: string
    circuit: string
  }>
}

async function loadZkModule(): Promise<ZKModule | null> {
  try {
    const moduleName = "@l.x/zk"
    const mod = (await import(/* @vite-ignore */ moduleName)) as Partial<ZKModule>
    if (typeof mod.prove === "function") {
      return mod as ZKModule
    }
    return null
  } catch {
    return null
  }
}

async function gatewayProve(claim: ClaimParams, witness: unknown): Promise<{
  proof: string
  publicInputs: string
  circuit: string
}> {
  const res = await fetch(gatewayUrl("/v1/zkp/prove"), {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    credentials: "include",
    body: JSON.stringify({ claim, witness }),
  })
  if (!res.ok) {
    throw new Error(`gatewayProve: ${res.status} ${res.statusText}`)
  }
  return (await res.json()) as { proof: string; publicInputs: string; circuit: string }
}

function newId(): string {
  // Crypto-strong UUID-ish identifier without pulling a dep.
  const g = globalThis as { crypto?: Crypto }
  if (g.crypto?.randomUUID) {
    return g.crypto.randomUUID()
  }
  const bytes = new Uint8Array(16)
  if (g.crypto?.getRandomValues) {
    g.crypto.getRandomValues(bytes)
  }
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("")
}

export interface ZKProveResult {
  proof: ZKProof
  /** True if the proof was generated by the gateway (witness left the device). */
  degraded: boolean
}

export function useZKProof() {
  const [generating, setGenerating] = useState(false)
  const [error, setError] = useState<string | undefined>()
  const [progress, setProgress] = useState<number>(0) // 0..100

  const prove = useCallback(
    async (claim: ClaimParams, witness: unknown): Promise<ZKProveResult | undefined> => {
      setGenerating(true)
      setError(undefined)
      setProgress(0)
      try {
        const zk = await loadZkModule()
        let raw: { proof: string; publicInputs: string; circuit: string }
        let degraded = false
        if (zk) {
          // Tick simulated progress while the worker churns; the real
          // module will replace this with onProgress events when shipped.
          const ticker = setInterval(() => {
            setProgress((p) => Math.min(95, p + 5))
          }, 250)
          try {
            raw = await zk.prove(claim, witness)
          } finally {
            clearInterval(ticker)
          }
        } else {
          raw = await gatewayProve(claim, witness)
          degraded = true
        }
        setProgress(100)
        const proof: ZKProof = {
          id: newId(),
          claim,
          proof: raw.proof,
          publicInputs: raw.publicInputs,
          circuit: raw.circuit,
          generatedAt: Date.now(),
        }
        confidentialStore.addProof(proof)
        return { proof, degraded }
      } catch (e) {
        setError(e instanceof Error ? e.message : String(e))
        return undefined
      } finally {
        setGenerating(false)
      }
    },
    [],
  )

  return { prove, generating, error, progress }
}
